package com.tinyDeveloper.na.ui.theme

import androidx.compose.ui.unit.dp

val NO_PADDING = 0.dp
val SMALL_PADDING = 4.dp
val MEDIUM_PADDING = 8.dp
val LARGE_PADDING = 12.dp
val EXTRA_LARGE_PADDING = 16.dp
val LARGEST_PADDING = 24.dp

val INPUT_CHAR_WIDTH = 42.dp
val INPUT_CHAR_HEIGHT = 56.dp

val NUMBER_PAD_BUTTON_SIZE = 64.dp

val PHONE_SCREEN_CONTENT_PADDING = 250.dp
val NUMBER_PAD_HEIGHT = 320.dp

val TOP_BAR_HEIGHT = 64.dp

val DROP_DOWN_BORDER_WIDTH = 1.dp

val DROP_DOWN_HEIGHT = 58.dp

val NOTIFICATION_ITEM_HEIGHT = 360.dp

val NOTIFICATION_SCREEN_IMAGE_HEIGHT = 300.dp

val NOTIFICATION_SCREEN_DESCRIPTION_HEIGHT = 300.dp

val NOTIFICATION_DETAILS_SCREEN_IMAGE_HEIGHT = 350.dp

val PROFILE_IMAGE_HEIGHT = 200.dp
val SHIMMER_NORMAL_HEIGHT = 55.dp
val SHIMMER_LARGE_HEIGHT = 80.dp
val SHIMMER_SMALL_HEIGHT = 48.dp

val SHIMMER_SMALL_TEXT = 26.dp
val SHIMMER_NORMAL_SMALL_TEXT = 28.dp
val SHIMMER_NORMAL_TEXT = 32.dp
val SHIMMER_EXTRA_SMALL = 12.dp
val SHIMMER_MEDIUM_SMALL = 16.dp

val PAGING_INDICATOR_WIDTH = 16.dp
val PAGING_INDICATOR_SPACING = 12.dp
